---
- name: Instalação do WordPress com Nginx na AWS
  hosts: all
  remote_user: ubuntu
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - preparo
    - php
    - nginx
    - wordpress
    - docker
#    - containers
